Touch Ups
drphilmarshall/Pangloss pull request #101
Opened 2016-10-20 02:42 UTC by davidthomas5412

This small PR contains basic touch ups. 

We still have not been able to fix issues with the plotting. Returning the imshow and world in plotting:150 seems will likely be one of the required fixes. There are also issues with sharing subplots and sharing plots objects in the overlay plots. We will hold off committing intermittent changes to this code until we resolve all known issues. 

In the future it might be good to centralize the plotting code and take a more object oriented approach with matplotlib.

2016-10-20 15:56 UTC, drphilmarshall commented
Great! Are you ready for this to be merged?

2016-10-20 16:01 UTC, drphilmarshall requested changes
Looks like you caught a few buglets as well as doing some useful lintering. Thanks! Can you please re-run all the notebooks listed in the index.ipynb and commit them as-is? They will then serve as an accurate record of our plotting failures... which then need to be issued.

2016-10-20 16:01 UTC, drphilmarshall commented on pangloss/foreground.py
> +        galaxies = self.return_galaxies(mag_lim, mass_lim, z_lim, ra_lim, dec_lim)
Excellent! Love Pep8 :-)

2016-10-20 16:01 UTC, drphilmarshall commented on pangloss/io.py
> +        number(s): extract integer or floating point from string
This reminds me: we should switch to numpydoc docstrings and get to work adding more. Can you issue this, please?

2016-10-20 16:37 UTC, davidthomas5412 commented on pangloss/io.py
> +        number(s): extract integer or floating point from string
Added [Issue 102](https://github.com/drphilmarshall/Pangloss/issues/102)

2016-10-27 16:51 UTC, davidthomas5412 commented
Hi Phil, reran the notebooks in commit 8d161faeb515f191d759427c610efcffc17bbbdb. Should be good to go.

2016-10-27 16:51 UTC, merged

2016-10-27 22:22 UTC, drphilmarshall commented
Good! Looks like we have at least one demo for Travis to run.