Issue 103 python data fetching
drphilmarshall/Pangloss pull request #108
Opened 2016-10-27 18:39 UTC by davidthomas5412

This pull requests sets up the data fetching and generally cleans up the structure of the project. It takes a reasonable departure from [Pull 3](https://github.com/davidthomas5412/Pangloss/pull/3) and (Pull 1)(https://github.com/davidthomas5412/Pangloss/pull/1) - which will now be obsolete.

Summary of changes:
1) data.py adds data fetching capability.
2) top level scripts have been moved into the bin directory.
3) setup.py and requirements.txt have been added to allow pip installations
4) docs have been updated to be consistent with above changes

Testing:
1) Confirmed pip install works on local machine
2) Confirmed downloads work from local machine

Next Steps:
Ready to merge after @drphilmarshall reviews.

2016-10-27 18:55 UTC, davidthomas5412 commented
This PR corresponds to (Issue 103)[https://github.com/drphilmarshall/Pangloss/issues/103]. After it is merged we will close the issue.

2016-10-27 22:40 UTC, drphilmarshall requested changes
Minor revision needed, mostly this looks good! :-)

2016-10-27 22:40 UTC, drphilmarshall commented on requirements.txt
> +astropy>=1.2.1
Do we need all these version numbers? And is the syntax really ">=" ? If so I can see how they are harmless.

2016-10-27 22:40 UTC, drphilmarshall commented on setup.py
> +    author="Phil Marshal",
There are two 'l's in Marshall :-) We should list Tom Collett, Spencer Everett and David Thomas as well.

2016-10-27 22:40 UTC, drphilmarshall commented on setup.py
> +        "License :: OSI Approved :: GNU General Public License (GPL)",
If we are not already using the MIT license we should switch, straight away.

2016-10-27 23:44 UTC, davidthomas5412 commented on requirements.txt
> +astropy>=1.2.1
The versions are the versions I have locally. I used >= to ensure that users wouldn't hit some issue from having an old package - although there is no evidence this is a problem. Sounds like you would like to get rid of the >= ?

2016-10-27 23:45 UTC, davidthomas5412 commented on setup.py
> +        "License :: OSI Approved :: GNU General Public License (GPL)",
Ok, current license is GPL, so I will change it to MIT on this branch.

2016-10-27 23:48 UTC, drphilmarshall commented
Great, thanks for changing the license! You might do a quick grep for "GPL"
to make sure all files are consistent with the new regime. And the README
may need updating too.

On Thu, Oct 27, 2016 at 4:45 PM, David Thomas <notifications@github.com>
wrote:

> *@davidthomas5412* commented on this pull request.
> ------------------------------
>
> In setup.py <https://github.com/drphilmarshall/Pangloss/pull/108>:
>
> > +from setuptools import setup
> +
> +setup(
> +    name="pangloss",
> +    version='0.0.1',
> +    author="Phil Marshal",
> +    author_email="pjm@slac.stanford.edu",
> +    url="https://github.com/drphilmarshall/pangloss",
> +    packages=["pangloss"],
> +    description="Line of sight weak lensing and inference.",
> +    long_description=open("README.md").read(),
> +    package_data={"": ["README.md", "LICENSE"]},
> +    include_package_data=True,
> +    classifiers=[
> +        "Development Status :: 4 - Beta",
> +        "License :: OSI Approved :: GNU General Public License (GPL)",
>
> Ok, current license is GPL, so I will change it to MIT on this branch.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/drphilmarshall/Pangloss/pull/108>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AArY9xaevnYPYEJkz0BdDy_8j4HT5MV0ks5q4Td9gaJpZM4Kir3->
> .
>

2016-10-28 00:34 UTC, davidthomas5412 commented
@drphilmarshall GPL references have been removed. Should be good to go.

2016-10-28 15:50 UTC, drphilmarshall approved these changes
Great! Thanks David

2016-10-28 15:50 UTC, merged